mv "1 The Galleries.gif" "the_galleries.gif"
mv "10 Punch and Julie.gif" "punch_and_julie.gif"
mv "11 Puppets.gif" "puppets.gif"
mv "12 Jeffrey Archer Memorial Fire Pit.gif" "jeffrey_archer_memorial_fire_pit.gif"
mv "13 Portrait Artist.gif" "portrait_artist.gif"
mv "14 Picnic Area.gif" "picnic_area.gif"
mv "15 Cinema.gif" "cinema.gif"
mv "16 Circus Tent.gif" "circus_tent.gif"
mv "17 Amusements.gif" "amusements.gif"
mv "18 BiG Rig Jig.gif" "big_rig_jig.gif"
mv "19 Parking.gif" "parking.gif"
mv "2 Model Village.gif" "model_village.gif"
mv "20 Security Check.gif" "security_check.gif"
mv "21 Exit Through The Gift Shop.gif" "exit_through_the_gift_shop.gif"
mv "22 Death Dance.gif" "death_dance.gif"
mv "23 Hallway.gif" "hallway.gif"
mv "24 Migrant Boats.gif" "migrant_boats.gif"
mv "25 Toilet Paper Table.gif" "toilet_paper_table.gif"
mv "26 Dolphin Toilet Bowl.gif" "dolphin_toilet_bowl.gif"
mv "27 Ferris Wheel.gif" "ferris_wheel.gif"
mv "28 Food Area.gif" "food_area.gif"
mv "3 Cinderella's Castle.gif" "cinderella's_castle.gif"
mv "4 Guerilla Island.gif" "guerilla_island.gif"
mv "5 Ben Long.gif" "ben_long.gif"
mv "6 Water Cannon Creek.gif" "water_cannon_creek.gif"
mv "7 Mini Gulf.gif" "mini_gulf.gif"
mv "8 Giant Pin Wheel.gif" "giant_pin_wheel.gif"
mv "9 Kids Enclosure.gif" "kids_enclosure.gif"
